import { Disclosure, DisclosureButton, DisclosurePanel } from '@headlessui/react'
import { MinusSmallIcon, PlusSmallIcon } from '@heroicons/react/24/outline'
import Footer from '../components/Footer';
import Header from '../components/Header';

const faqs = [
  {
    question: "1. Acceptance of Terms",
    answer:
      "By accessing or using the App, you agree to these Terms. If you do not agree, do not use the App.",
  },
  {
    question: "2. Description of Service",
    answer:
      "The App provides tools for journaling, mood tracking, and AI-powered insights for personal growth and mental wellness. It is not intended as a substitute for professional medical, psychological, or therapeutic advice.",
  },
  {
    question: "3. Eligibility",
    answer:
      "The App is intended for users aged 13 and older. If you are under the age of majority in your jurisdiction, you must have the consent of a parent or legal guardian to use the App.",
  },
  {
    question: "4. Modifications to Terms",
    answer:
      "We reserve the right to update or modify these Terms at any time. Continued use of the App after any changes constitutes your acceptance of the revised Terms.",
  },
  {
    question: "5. User Accounts",
    answer:
      "To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity associated with your account.",
  },
  {
    question: "6. In-App Purchases and Subscriptions",
    answer:
      "Certain features may require payment through in-app purchases or subscriptions. All transactions are managed by third-party platforms, and their refund policies apply. You are responsible for managing your subscription preferences directly with the platform.",
  },
  {
    question: "7. User Content and Data Usage",
    answer: (
      <>
        <p className="mb-4">
          You retain full ownership of the content you create or upload to the App, including journal entries, mood logs, voice memos, and images (“User Content”). We do not claim ownership over your personal data. However, by using the App, you grant Mindwell World LLC a non-exclusive, worldwide, royalty-free, transferable, and sublicensable license to use your User Content solely to operate, improve, and enhance the Mindwell App and related services, as well as supporting the broader business operations of Mindwell World LLC.
        </p>
        <p className="mb-2">This includes, but is not limited to, the following purposes:</p>
        <ul className="list-disc pl-6 mb-4 text-gray-300">
          <li>Delivering personalized insights using artificial intelligence (AI), including chatbots, summaries, and suggestions based on your data</li>
          <li>Processing content through third-party AI providers and/or proprietary models</li>
          <li>Improving and training AI/ML models, including through aggregated or anonymized data</li>
          <li>Analyzing behavioral trends to guide feature development and improve emotional wellness tools</li>
          <li>Producing anonymized reports or statistics for research, business development, or marketing</li>
          <li>Performing usability testing and interface improvements</li>
          <li>Protecting system integrity and complying with legal requirements</li>
        </ul>
        <p className="mb-4">
          <strong>We do not sell your data.</strong> We do not publicly disclose your journal entries, media, or personal content. Human review of content is limited to exceptional cases such as debugging, abuse investigation, or legal compliance.
        </p>
        <p className="mb-2">You agree not to upload content that:</p>
        <ul className="list-disc pl-6 mb-4 text-gray-300">
          <li>Violates any laws or regulations</li>
          <li>Infringes upon intellectual property, privacy, or other rights</li>
          <li>Is abusive, threatening, deceptive, or harmful</li>
        </ul>
        <p className="mb-0">
          You may revoke this license at any time by deleting your account and requesting data deletion, subject to our retention obligations described in our Privacy Policy.
        </p>
      </>
    )
  },
  {
    question: "8. Data Retention",
    answer:
      "We retain data only as long as necessary to provide the Service and fulfill legal obligations. Deleted accounts are processed within 90 days, unless otherwise required by law.",
  },
  {
    question: "9. AI-Generated Content",
    answer:(
      <>
        <p className="mb-4">
          The App provides suggestions and insights generated by AI systems, including third-party tools. These are for informational and self-reflective purposes only and are not a replacement for professional mental health care.
        </p>
        <ul className="list-disc pl-6 mb-4 text-gray-300">
          <li>AI content may occasionally be incorrect, biased, or inappropriate</li>
          <li>You accept responsibility for how you interpret or act upon AI-generated content</li>
        </ul>
      </>
    )
  },
  {
    question: "10. AI Training and Model Safety",
    answer:
      "Your content may be used (in anonymized or aggregated form) to improve proprietary AI models. We enforce strict safeguards to limit exposure of personally identifiable information and ensure ethical AI use.",
  },
  {
    question: "11. Privacy",
    answer:
    (
      <p className="text-base/7 text-gray-300">
        Your privacy is important to us. Please review our{" "}
        <a
          href="https://www.mindwellworld.com/privacy"
          className="text-indigo-400 underline hover:text-indigo-300 transition-colors duration-200"
          target="_blank"
          rel="noopener noreferrer"
        >
          Privacy Policy
        </a>{" "}
        to understand how we collect, use, and protect your personal data.
      </p>
    )
  },
  {
    question: "12. Limitation of Liability",
    answer:
      "The App and all content are provided “as is” without warranties of any kind. We are not liable for any damages, including but not limited to data loss, service interruptions, or adverse outcomes resulting from use of the App or reliance on AI-generated content.",
  },
  {
    question: "13. Indemnity",
    answer:
      "You agree to indemnify and hold harmless Mindwell World LLC and its affiliates, directors, employees, and agents from any claims, damages, or expenses arising from your use of the App, your User Content, or your violation of these Terms.",
  },
  {
    question: "14. Termination",
    answer:
      "We reserve the right to suspend or terminate your access to the App at any time for violating these Terms or engaging in misuse.",
  },
  {
    question: "15. Governing Law",
    answer:
      "These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles.",
  },
  {
    question: "16. Dispute Resolution",
    answer:
      "Any disputes arising from these Terms or use of the App will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. You waive the right to participate in class actions. You may opt out of arbitration by notifying us in writing within 30 days of first agreeing to these Terms.",
  },
  {
    question: "17. Contact Us",
    answer: (
      <>
        <p className="mb-2">
          For questions, concerns, or legal notices, please contact us at:
        </p>
        <ul className="list-none pl-0 space-y-1 text-gray-300">
          <li>
            Email:{" "}
            <a
              href="mailto:support@mindwell.io"
              className="text-indigo-400 underline hover:text-indigo-300 transition-colors duration-200"
            >
              support@mindwell.io
            </a>
          </li>
          <li>
            X (Twitter):{" "}
            <a
              href="https://twitter.com/MindwellWorld"
              className="text-indigo-400 underline hover:text-indigo-300 transition-colors duration-200"
              target="_blank"
              rel="noopener noreferrer"
            >
              @MindwellWorld
            </a>
          </li>
        </ul>
      </>
    )
    },

]

export default function Terms() {
  return (
    <div className="bg-gradient-to-br from-[#2F52E0] via-[#000000] to-[#000000]">
      <Header />
      <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8 lg:py-40">
        <div className="mx-auto max-w-4xl">
          <h2 className="text-4xl font-semibold tracking-tight text-white sm:text-5xl">Terms and Conditions</h2>
          <div className="mt-10 text-base/7 text-gray-300 space-y-4">
            <p>
              Thank you for using the Mindwell App and supporting our mission and vision!
            </p>
            <p>
              These Terms and Conditions (the “Terms”) govern your access to and use of the Mindwell App (the “App,” “Mindwell App,” or “Mindwell World App”), a digital product provided by Mindwell World LLC (“Mindwell,” “we,” “us,” or “our”). The App is the flagship product of Mindwell World LLC, a company dedicated to elevating the mental wellness around the world.
            </p>
            <p>
              By accessing or using the App, you agree to be bound by these Terms, which constitute a legal agreement between you and Mindwell World LLC. If you do not agree with these Terms, you may not access or use the App.
            </p>
            <p className="font-semibold text-white uppercase">
              Arbitration Notice: <span className="font-normal normal-case text-gray-300">You agree that disputes between you and Mindwell World LLC will be resolved through binding individual arbitration. You waive your right to participate in a class action or class-wide arbitration. See the “Dispute Resolution” section below for details, including how to opt out.</span>
            </p>
          </div>
          <dl className="mt-16 divide-y divide-white/10">
            {faqs.map((faq) => (
              <Disclosure key={faq.question} as="div" className="py-6 first:pt-0 last:pb-0">
                <dt>
                  <DisclosureButton className="group flex w-full items-start justify-between text-left text-white">
                    <span className="text-base/7 font-semibold">{faq.question}</span>
                    <span className="ml-6 flex h-7 items-center">
                      <PlusSmallIcon aria-hidden="true" className="size-6 group-data-open:hidden" />
                      <MinusSmallIcon aria-hidden="true" className="size-6 group-not-data-open:hidden" />
                    </span>
                  </DisclosureButton>
                </dt>
                <DisclosurePanel as="dd" className="mt-2 pr-12">
                  <div className="text-base/7 text-gray-300">{faq.answer}</div>
                </DisclosurePanel>
              </Disclosure>
            ))}
          </dl>
        </div>
      </div>

      <Footer />

    </div>
  )
}
